[package]
name = "shortest-color-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
shortest-color = "*"
wasm-bindgen = "0.2"

[profile.release]
opt-level = "z"
lto = true